name: Version Check

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    
jobs:
  check_version:
    runs-on: ubuntu-latest
    
    env:
      WP_VERSION_FILE: 'style.css'
      USES_PACKAGE_JSON: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - id: wp_version
        run: echo "::set-output name=version::$(perl -n -e'/Version:\s*(\d.\d.\d)/ && print $1' $WP_VERSION_FILE)"
      - name: Check if wp_version is set
        if: ${{ !steps.wp_version.outputs.version }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('wp_version not set')
      - id: package_json_version
        if: $USES_PACKAGE_JSON
        run: |         
          PACKAGE_JSON_VERSION=$(npm pkg get version | sed 's/"//g')
          echo "Version: $PACKAGE_JSON_VERSION"
          echo "::set-output name=version::$PACKAGE_JSON_VERSION"
      - name: Check if package_json_version is set
        if: ${{ $USES_PACKAGE_JSON && !steps.package_json_version.outputs.version }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('wp_version not set')
      - name: Check if versions are equal
        if: ${{ $USES_PACKAGE_JSON && steps.wp_version.outputs.version != steps.package_json_version.outputs.version }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('wp_version and package_json_version must be the same')
      - name: Get latest tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
         fallback: 0.0.0
      - name: Get possible next versions
        id: nexttags
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Validate version
        if:  ${{ steps.nexttags.outputs.major != steps.versionstrings.outputs.wp_version && steps.nexttags.outputs.minor != steps.versionstrings.outputs.wp_version && steps.nexttags.outputs.patch != steps.versionstrings.outputs.wp_version }} 
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Invalid version')
